### PR TITLE
Applying toolkit - first attempt

### PR DESCRIPTION
**Pull request by dprokop**
WIP

### CODE REVIEW

**Comment by algenty** [comment]
I'll trying it

**Comment by algenty** [comment]
Not works with your changes on grafana 6.4 :  
Error loading panel plugin: agenty-flowcharting-panel TypeError: Cannot read property 'FlowchartCtrl' of undefined
    at Object.get [as PanelCtrl] (module.js:9)
    at O (system.js:4)
    at k (system.js:4)
    at system.js:4

**Comment by algenty** [comment]
i move it in branch 0.6.0_grafana_toolkit

**Comment by dprokop** [comment]
@algenty hey, this is Dominik form Grafana. Together with @ryantxu we were looking at your plugin and decided to enable JS files handling in grafana-toolkit. Can you please try out the changes I have made with grafana-toolkit@canary version? It builds on my machine (using `grafana-toolkit plugin:dev`) but we are encountering some problems with the tests. Would be awesome if you could test changes introduced in this PR agains grafana-toolkit@canary version, and try fixing the tests.

**Comment by algenty** [comment]
Hi @dprokop 
The migration works a little, i see graph but it bug in edit mode see
https://github.com/grafana/grafana/issues/20148

**Pull request merged**
