### PR TITLE
Use toolkit for build, not grunt

### PR DESCRIPTION
**Pull request by ryantxu**
Depends on #62

This PR updates the build to use toolkit for the build.

NOTE: the tests are not passing.  It is something with getting an express server setup and running propertly (I think)

### CODE REVIEW

**Comment by dprokop** [comment]
@ryantxu is the plugin:dev working for you? I'm getting error with css-loader being missing even though it is installed.

**Comment by dprokop** [comment]
@ryantxu not getting it now, i think I had some issues with outdated node_modules

**Comment by algenty** [comment]
i undestand for grunt but how to copy external files with toolkit in dist like picture or xml from draw.io ?

**Comment by ryantxu** [comment]
> i undestand for grunt but how to copy external files with toolkit in dist like picture or xml from draw.io 

webpack should be able to do that for us -- is the question how to keep the imports external? or to put them in directly

**Comment by ryantxu** [comment]
@algenty -- are you on grafana slack or some other text message platform?  It would be nice to sync up :)

**Comment by algenty** [comment]
Can you invite me on grafana slack, my email : arnaud.genty@gmail.com. or with the mail of project : grafana.flowcharting@gmail.com

**Comment by algenty** [comment]
i merge it in branch 0.6.0_01_optimize_set
Sorry if I ask beginner questions but I'm not a developer, 
6 months ago I didn't know js, nodejs, babel, webpack and others tools. it's new for me ;)
I learned everything during my personal time

**Pull request merged**
